### ISSUE TITLE
Header Image in Docs Renders Inside out

### ISSUE THREAD

**Issue by LongLiveCHIEF** [cujarrett/learning-terraform#1]

**Comment by cujarrett** [comment]
@LongLiveCHIEF - Sorry I don't follow. What's the fix?

**Comment by LongLiveCHIEF** [comment]
Try taking it out and putting it back in.

**Comment by cujarrett** [comment]
@LongLiveCHIEF - Could you add a screenshot of the problem by chance?

**Comment by LongLiveCHIEF** [comment]
Requires effort. Will close and open another ticket with slightly different title.
